name: Deploy

# Trigger workflow on push or pull request events on main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Authenticate to the server via ssh
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: "cd api-anxiety.studyatsac.com && ./.scripts/deploy.sh"
